# Generated by Django 3.2.13 on 2022-10-12 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_alter_module_segmentacion_module_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_segmentacion',
            name='module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.modules'),
        ),
    ]
