# Generated by Django 3.2.13 on 2022-10-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_alter_module_segmentacion_module_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_modules',
            name='state',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='module_segmentacion',
            name='state',
            field=models.BooleanField(null=True),
        ),
    ]
