# Generated by Django 3.2.13 on 2022-10-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0005_auto_20221012_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module_segmentacion',
            old_name='type',
            new_name='name',
        ),
    ]
