# Generated by Django 3.2.13 on 2022-10-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_rename_type_module_segmentacion_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module_segmentacion',
            name='module_id',
        ),
        migrations.AddField(
            model_name='module_segmentacion',
            name='module_id',
            field=models.ManyToManyField(to='modulos.modules'),
        ),
    ]
