# Generated by Django 3.2.13 on 2022-10-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0008_auto_20221015_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_segmentacion',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
