# Generated by Django 3.2.13 on 2022-10-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0011_auto_20221024_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='codigo',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
