# Generated by Django 3.2.13 on 2022-10-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0012_modules_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='codigo',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
