# Generated by Django 3.2.13 on 2022-10-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0013_alter_modules_codigo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer_modules',
            table='service_customer_modules',
        ),
        migrations.AlterModelTable(
            name='module_segmentacion',
            table='service_module_segmentation',
        ),
        migrations.AlterModelTable(
            name='modules',
            table='service_modules',
        ),
    ]
