# Generated by Django 3.2.13 on 2022-10-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0003_auto_20221015_0209'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ciudad',
            table='service_cities',
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='service_provinces',
        ),
    ]
