# Generated by Django 3.2.13 on 2022-09-27 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0002_alter_ciudad_province_id'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit_cuil', models.PositiveIntegerField(default=0)),
                ('business_name', models.CharField(max_length=128, unique=True)),
                ('phone', models.PositiveIntegerField(default=0)),
                ('mobile', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=254)),
                ('height', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('details', models.CharField(max_length=254)),
                ('bank_account_id', models.CharField(max_length=254)),
                ('state', models.BooleanField(default=False)),
                ('city_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ubicacion.ciudad')),
                ('persons_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personas.persona')),
            ],
        ),
    ]
