# Generated by Django 3.2.13 on 2022-10-03 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0002_alter_ciudad_province_id'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ubicacion.ciudad'),
        ),
    ]
