# Generated by Django 3.2.13 on 2022-10-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuit_cuil',
            field=models.PositiveIntegerField(default=False, unique=True),
        ),
    ]
