# Generated by Django 3.2.13 on 2022-10-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_cuit_cuil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='state',
            field=models.BooleanField(),
        ),
    ]
