# Generated by Django 3.2.13 on 2022-10-15 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_state'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='customer',
        ),
    ]
