# Generated by Django 3.2.13 on 2022-10-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuit_cuil',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
