# Generated by Django 3.2.13 on 2022-10-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20221029_0434'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='service_customer',
        ),
        migrations.AlterModelTable(
            name='cliente_user',
            table='service_customer_user',
        ),
    ]
