# Generated by Django 3.2.13 on 2022-10-18 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_alter_cliente_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dns1', models.CharField(max_length=30)),
                ('dns2', models.CharField(max_length=30)),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='BD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBD', models.CharField(max_length=30, null=True, unique=True)),
                ('userBD', models.CharField(max_length=30)),
                ('passwordBD', models.CharField(max_length=30)),
                ('currentSize', models.CharField(max_length=30)),
                ('TotalSize', models.CharField(max_length=30)),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
            ],
        ),
    ]
