# Generated by Django 3.2.13 on 2022-10-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bd',
            options={'ordering': ['name_bd']},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='bd',
            old_name='nameBD',
            new_name='name_bd',
        ),
        migrations.RenameField(
            model_name='bd',
            old_name='passwordBD',
            new_name='password_bd',
        ),
        migrations.RenameField(
            model_name='bd',
            old_name='userBD',
            new_name='user_bd',
        ),
        migrations.AlterModelTable(
            name='bd',
            table='customerBD',
        ),
        migrations.AlterModelTable(
            name='website',
            table='website',
        ),
    ]
