# Generated by Django 3.2.13 on 2022-10-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20221018_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='parrafo_1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='parrafo_2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='parrafo_3',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
