# Generated by Django 3.2.13 on 2022-09-27 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0002_alter_ciudad_province_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('birthday', models.DateField(null=True)),
                ('phone', models.PositiveIntegerField(default=0)),
                ('mobile', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=254)),
                ('address_number', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateField(null=True)),
                ('last_modified_date', models.DateField(null=True)),
                ('city_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ubicacion.ciudad')),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
