# Generated by Django 3.2.13 on 2022-10-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_persona_city_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['dni']},
        ),
        migrations.AlterField(
            model_name='persona',
            name='address_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mobile',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='persona',
            table='persons',
        ),
    ]
