# Generated by Django 3.2.13 on 2022-10-25 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20221015_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='user_id',
        ),
    ]
