# Generated by Django 3.2.13 on 2022-10-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_remove_persona_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.PositiveIntegerField(max_length=11, unique=True),
        ),
    ]
