# Generated by Django 3.2.13 on 2022-10-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0010_auto_20221029_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
