# Generated by Django 3.2.13 on 2022-10-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0011_alter_persona_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='service_persons',
        ),
    ]
